name: e_commerce
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  # HELPER
  equatable: ^2.0.3
  logger: ^1.1.0
  http: ^0.13.4
  shared_preferences: ^2.0.11
  get_it: ^7.2.0
  image_picker: ^0.8.4+8

  # WIDGET
  bot_toast: ^4.0.1
  flutter_dialogs: ^2.1.1

  # STATE MANAGEMENT
  flutter_bloc: ^8.0.0
  auto_route: ^3.2.4

  # FIREBASE
  # GITHUB

  # FLUTTER
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  firebase_core: ^1.14.1
  cloud_firestore: ^3.1.12
  firebase_storage: ^10.2.12
  firebase_auth: ^3.3.14
  google_sign_in: ^5.2.3
  intl: ^0.17.0
  firebase_messaging: ^11.2.13
  flutter_local_notifications: ^9.4.0

  flutter_dotenv: ^5.0.2
  firebase_dynamic_links: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  auto_route_generator: ^3.2.0
  test: ^1.19.5

  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/fonts/
    - .env
    - .env.development
    - .env.production
  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/metropolis/Metropolis-Thin.otf
          weight: 100
        - asset: assets/fonts/metropolis/Metropolis-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/metropolis/Metropolis-Light.otf
          weight: 300
        - asset: assets/fonts/metropolis/Metropolis-Regular.otf
          weight: 400
        - asset: assets/fonts/metropolis/Metropolis-Medium.otf
          weight: 500
        - asset: assets/fonts/metropolis/Metropolis-SemiBold.otf
          weight: 600
        - asset: assets/fonts/metropolis/Metropolis-Bold.otf
          weight: 700
        - asset: assets/fonts/metropolis/Metropolis-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/metropolis/Metropolis-Black.otf
          weight: 900
