import 'package:e_commerce/src/models/categories_model.dart';
import 'package:e_commerce/src/models/delivery_method_model.dart';
import 'package:e_commerce/src/models/products_model.dart';
import 'package:e_commerce/src/models/promotions_model.dart';
import 'package:e_commerce/src/models/review_model.dart';

final List<XProduct> listProduct = [
  XProduct(
    id: '1',
    name: 'Sitlly',
    image:
        'https://firebasestorage.googleapis.com/v0/b/e-conmmerce.appspot.com/o/products%2F147da579254b3012302de5304dcb0db0.png?alt=media&token=44c510d5-513f-4728-8130-3a542129d42a',
    star: 10,
    type: 'Sport Dress',
    color: '',
    size: '',
    originalPrice: 22.0,
    discount: 15.0,
    currentPrice: 19.0,
    newProduct: false,
    idCategory: '11',
    nameCategory: 'Dresses',
    soldOut: true,
    amount: 0,
    favorite: false,
  ),
  XProduct(
    id: '2',
    name: 'Dorothy Perkins',
    image:
        'https://firebasestorage.googleapis.com/v0/b/e-conmmerce.appspot.com/o/products%2Fd2aebb9b52db31deea621f309362bab4.png?alt=media&token=85903119-98f7-4123-a33a-4a7db9192576',
    star: 10,
    type: 'Sport Dress',
    color: '',
    size: '',
    originalPrice: 14.0,
    discount: 20.0,
    currentPrice: 12.0,
    newProduct: false,
    idCategory: '11',
    nameCategory: 'Dresses',
    soldOut: false,
    amount: 0,
    favorite: false,
  ),
  XProduct(
    id: '3',
    name: 'Dorothy Perkins',
    image:
        'https://firebasestorage.googleapis.com/v0/b/e-conmmerce.appspot.com/o/products%2Fbe1de61431deda2032c364122b021da3.png?alt=media&token=af6da237-25e5-4641-81f5-d5f591a93076',
    star: 10,
    type: 'Blouse',
    color: '',
    size: '',
    originalPrice: 21.0,
    discount: 20.0,
    currentPrice: 14.0,
    newProduct: false,
    idCategory: '2',
    nameCategory: 'Shirts & Blouses',
    soldOut: false,
    amount: 0,
    favorite: false,
  ),
  XProduct(
    id: '4',
    name: 'Cool',
    image:
        'https://firebasestorage.googleapis.com/v0/b/e-conmmerce.appspot.com/o/products%2F9999902f1278824120c0dec8686180c5.png?alt=media&token=6c022b6e-bf26-41ee-be83-1707e51cf888',
    star: 0,
    type: 'Jeans',
    color: '',
    size: '',
    originalPrice: 45.0,
    discount: 0.0,
    currentPrice: 0.0,
    newProduct: true,
    idCategory: '8',
    nameCategory: 'Jeans',
    soldOut: false,
    amount: 0,
    favorite: false,
  ),
  XProduct(
    id: '5',
    name: 'T-shirt',
    image:
        'https://firebasestorage.googleapis.com/v0/b/e-conmmerce.appspot.com/o/products%2F953d61faf9fd666897e97a67e9857028.png?alt=media&token=0801dfdd-b396-488b-b4c8-1b8e6f8ef7cd',
    star: 10,
    type: 'LOST Ink',
    color: '',
    size: '',
    originalPrice: 12.0,
    discount: 0.0,
    currentPrice: 0.0,
    newProduct: false,
    idCategory: '2',
    nameCategory: 'Shirts & Blouses',
    soldOut: false,
    amount: 0,
    favorite: false,
  ),
  XProduct(
    id: '6',
    name: 'Olivier',
    image:
        'https://firebasestorage.googleapis.com/v0/b/e-conmmerce.appspot.com/o/products%2F3bcf169c1f1c4b22fc8fc4b86176e01a.png?alt=media&token=0c465eb8-8016-43df-bfc2-c225d17670b0',
    star: 10,
    type: 'Shirt',
    color: '',
    size: '',
    originalPrice: 52.0,
    discount: 0.0,
    currentPrice: 0.0,
    newProduct: false,
    idCategory: '2',
    nameCategory: 'Shirts & Blouses',
    soldOut: false,
    amount: 0,
    favorite: false,
  ),
  XProduct(
    id: '7',
    name: 'OVS',
    image:
        'https://firebasestorage.googleapis.com/v0/b/e-conmmerce.appspot.com/o/products%2F3bcf169c1f1c4b22fc8fc4b86176e01a.png?alt=media&token=0c465eb8-8016-43df-bfc2-c225d17670b0',
    star: 0,
    type: 'Blouse',
    color: '',
    size: '',
    originalPrice: 30.0,
    discount: 0.0,
    currentPrice: 0.0,
    newProduct: true,
    idCategory: '2',
    nameCategory: 'Shirts & Blouses',
    soldOut: false,
    amount: 0,
    favorite: false,
  ),
  XProduct(
    id: '8',
    name: 'Shirt',
    image:
        'https://firebasestorage.googleapis.com/v0/b/e-conmmerce.appspot.com/o/products%2F2e83ffc52e71ad79aa63042d84df66ea.png?alt=media&token=8bfc8f2b-c7e8-47f7-a546-f7093a513389',
    star: 3,
    type: 'Topshop',
    color: '',
    size: '',
    originalPrice: 51.0,
    discount: 0.0,
    currentPrice: 0.0,
    newProduct: false,
    idCategory: '2',
    nameCategory: 'Shirts & Blouses',
    soldOut: false,
    amount: 0,
    favorite: false,
  ),
  XProduct(
    id: '9',
    name: 'Blouse',
    image:
        'https://firebasestorage.googleapis.com/v0/b/e-conmmerce.appspot.com/o/products%2F147da579254b3012302de5304dcb0db0.png?alt=media&token=44c510d5-513f-4728-8130-3a542129d42a',
    star: 0,
    type: 'Dorothy Perkins',
    color: '',
    size: '',
    originalPrice: 34.0,
    discount: 0.0,
    currentPrice: 0.0,
    newProduct: false,
    idCategory: '2',
    nameCategory: 'Shirts & Blouses',
    soldOut: false,
    favorite: false,
    amount: 0,
  ),
  XProduct(
    id: '10',
    name: 'Dorothy Perkins',
    image:
        'https://firebasestorage.googleapis.com/v0/b/e-conmmerce.appspot.com/o/products%2F2e83ffc52e71ad79aa63042d84df66ea.png?alt=media&token=8bfc8f2b-c7e8-47f7-a546-f7093a513389',
    star: 10,
    type: 'Evening Dress',
    color: '',
    size: '',
    originalPrice: 15.0,
    discount: 20.0,
    currentPrice: 12.0,
    newProduct: false,
    idCategory: '11',
    nameCategory: 'Dresses',
    soldOut: false,
    amount: 0,
    favorite: false,
  ),
  XProduct(
    id: "11",
    name: 'Mango Boy',
    image:
        'https://firebasestorage.googleapis.com/v0/b/e-conmmerce.appspot.com/o/products%2F3bcf169c1f1c4b22fc8fc4b86176e01a.png?alt=media&token=0c465eb8-8016-43df-bfc2-c225d17670b0',
    star: 0,
    type: 'T-Shirt Sailing',
    color: '',
    size: '',
    originalPrice: 10.0,
    discount: 0.0,
    currentPrice: 0.0,
    newProduct: true,
    idCategory: '2',
    nameCategory: 'Shirts & Blouses',
    soldOut: false,
    amount: 0,
    favorite: false,
  ),
  XProduct(
    id: "12",
    name: 'Pullover',
    image:
        'https://firebasestorage.googleapis.com/v0/b/e-conmmerce.appspot.com/o/products%2F3bcf169c1f1c4b22fc8fc4b86176e01a.png?alt=media&token=0c465eb8-8016-43df-bfc2-c225d17670b0',
    star: 3,
    type: 'Mango',
    color: '',
    size: '',
    originalPrice: 51.0,
    discount: 0.0,
    currentPrice: 0.0,
    newProduct: false,
    idCategory: '2',
    nameCategory: 'Shirts & Blouses',
    soldOut: false,
    amount: 0,
    favorite: false,
  ),
  XProduct(
    id: "13",
    name: 'LIME',
    image:
        'https://firebasestorage.googleapis.com/v0/b/e-conmmerce.appspot.com/o/products%2F953d61faf9fd666897e97a67e9857028.png?alt=media&token=0801dfdd-b396-488b-b4c8-1b8e6f8ef7cd',
    star: 10,
    type: 'Shirt',
    color: '',
    size: '',
    originalPrice: 32.0,
    discount: 0.0,
    currentPrice: 0.0,
    newProduct: false,
    idCategory: '2',
    nameCategory: 'Shirts & Blouses',
    soldOut: false,
    amount: 0,
    favorite: false,
  ),
  XProduct(
    id: "14",
    name: 'Berries',
    image:
        'https://firebasestorage.googleapis.com/v0/b/e-conmmerce.appspot.com/o/products%2F9999902f1278824120c0dec8686180c5.png?alt=media&token=6c022b6e-bf26-41ee-be83-1707e51cf888',
    star: 0,
    type: 'T-Shirt',
    color: '',
    size: '',
    originalPrice: 55.0,
    discount: 30.0,
    currentPrice: 39.0,
    newProduct: false,
    idCategory: '2',
    nameCategory: 'Shirts & Blouses',
    soldOut: false,
    amount: 0,
    favorite: false,
  ),
  XProduct(
    id: "15",
    name: 'Mango',
    image:
        'https://firebasestorage.googleapis.com/v0/b/e-conmmerce.appspot.com/o/products%2Fbe1de61431deda2032c364122b021da3.png?alt=media&token=af6da237-25e5-4641-81f5-d5f591a93076',
    star: 3,
    type: 'T-Shirt SPANISH',
    color: '',
    size: '',
    originalPrice: 9.0,
    discount: 0.0,
    currentPrice: 0.0,
    newProduct: false,
    idCategory: '2',
    nameCategory: 'Shirts & Blouses',
    soldOut: false,
    amount: 0,
    favorite: false,
  ),
  XProduct(
      id: "16",
      name: 'Mango',
      image:
          'https://firebasestorage.googleapis.com/v0/b/e-conmmerce.appspot.com/o/products%2Fd2aebb9b52db31deea621f309362bab4.png?alt=media&token=85903119-98f7-4123-a33a-4a7db9192576',
      star: 0,
      type: 'Longsleeve Violeta',
      color: '',
      size: '',
      originalPrice: 46.0,
      discount: 0.0,
      currentPrice: 0.0,
      idCategory: '2',
      nameCategory: 'Shirts & Blouses',
      soldOut: false,
      amount: 0,
      favorite: false,
      newProduct: true),
];

final List<XCategories> listCategories = [
  XCategories(id: '1', name: 'Tops'),
  XCategories(id: '2', name: 'Shirts & Blouses'),
  XCategories(id: '3', name: 'Cardigans & Sweaters'),
  XCategories(id: '4', name: 'Knitwear'),
  XCategories(id: '5', name: 'Blazers'),
  XCategories(id: '6', name: 'Outerwear'),
  XCategories(id: '7', name: 'Pants'),
  XCategories(id: '8', name: 'Jeans'),
  XCategories(id: '9', name: 'Shorts'),
  XCategories(id: '10', name: 'Skirts'),
  XCategories(id: '11', name: 'Dresses'),
];
final List<XPromotion> listPromotions = [
  XPromotion(
      id: '1',
      name: 'Personal offer',
      code: 'mypromocode2020',
      discount: 22,
      image:
          'https://firebasestorage.googleapis.com/v0/b/e-conmmerce.appspot.com/o/promos%2Fbg.png?alt=media&token=8f02ea4f-6e01-4199-b875-7cfe8384da51',
      timeRemaining: 6),
  XPromotion(
      id: '2',
      name: 'Summer Sale',
      code: 'summer2020',
      discount: 15,
      image:
          'https://firebasestorage.googleapis.com/v0/b/e-conmmerce.appspot.com/o/promos%2F10a65d667854ec91d5944928692f967e.png?alt=media&token=5a611ccb-319a-4984-b2b9-e5660370889e',
      timeRemaining: 23),
  XPromotion(
      id: '3',
      name: 'Personal offer1',
      code: 'promocode2020',
      discount: 10,
      image:
          'https://firebasestorage.googleapis.com/v0/b/e-conmmerce.appspot.com/o/promos%2Fbg1.png?alt=media&token=a465a53d-0fa1-41b6-b69b-637b4c1ff731',
      timeRemaining: 6),
];
final List<XReview> listReviews = [
  XReview(
      id: '1',
      images: [],
      idUser: 'VJVYQApfYaQftUUtZph6CKWptGB2',
      imageAvatar:
          'https://firebasestorage.googleapis.com/v0/b/e-conmmerce.appspot.com/o/user%2Fimage%202.png?alt=media&token=b1477306-e913-440a-9b93-6184805e341b',
      name: 'Helene Moore',
      content:
          'The dress is great! Very classy and comfortable. It fit perfectly! I\'m 5\'7" and 130 pounds. I am a 34B chest. This dress would be too long for those who are shorter but could be hemmed. I wouldn\'t recommend it for those big chested as I am smaller chested and it fit me perfectly. The underarms were not too wide and the dress was made well.',
      star: 4,
      time: 'June 5, 2019'),
  XReview(
      id: '1',
      images: [],
      idUser: 'VJVYQApfYaQftUUtZph6CKWptGB2',
      imageAvatar:
          'https://firebasestorage.googleapis.com/v0/b/e-conmmerce.appspot.com/o/user%2Fimage%203.png?alt=media&token=617d95e2-2bbe-4046-bc17-9ec9d40d74ab',
      name: 'Kate Doe',
      content:
          'The dress is great! Very classy and comfortable. It fit perfectly! I\'m 5\'7" and 130 pounds. I am a 34B chest. This dress would be too long for those who are shorter but could be hemmed. I wouldn\'t recommend it for those big chested as I am smaller chested and it fit me perfectly. The underarms were not too wide and the dress was made well.',
      star: 4,
      time: 'June 5, 2019'),
  XReview(
      id: '1',
      imageAvatar:
          'https://firebasestorage.googleapis.com/v0/b/e-conmmerce.appspot.com/o/user%2Fimage%204.png?alt=media&token=b72a934a-d77d-4b65-865e-358959512b18',
      name: 'Kim Shine',
      content:
          'I loved this dress so much as soon as I tried it on I knew I had to buy it in another color. I am 5\'3 about 155lbs and I carry all my weight in my upper body. When I put it on I felt like it thinned me put and I got so many compliments.',
      star: 4,
      idUser: 'VJVYQApfYaQftUUtZph6CKWptGB2',
      images: [
        'https://firebasestorage.googleapis.com/v0/b/e-conmmerce.appspot.com/o/user%2Fimage%202.png?alt=media&token=b1477306-e913-440a-9b93-6184805e341b',
        'https://firebasestorage.googleapis.com/v0/b/e-conmmerce.appspot.com/o/user%2Fimage%202.png?alt=media&token=b1477306-e913-440a-9b93-6184805e341b'
      ],
      time: 'August 13, 2019'),
  XReview(
      id: '1',
      idUser: 'VJVYQApfYaQftUUtZph6CKWptGB2',
      images: [
        'https://firebasestorage.googleapis.com/v0/b/e-conmmerce.appspot.com/o/user%2Fimage%202.png?alt=media&token=b1477306-e913-440a-9b93-6184805e341b',
        'https://firebasestorage.googleapis.com/v0/b/e-conmmerce.appspot.com/o/user%2Fimage%202.png?alt=media&token=b1477306-e913-440a-9b93-6184805e341b'
      ],
      imageAvatar:
          'https://firebasestorage.googleapis.com/v0/b/e-conmmerce.appspot.com/o/user%2Fimage.png?alt=media&token=a32ed306-7473-4968-9946-8de4bcab6d33',
      name: 'Matilda Brown',
      content:
          'I loved this dress so much as soon as I tried it on I knew I had to buy it in another color. I am 5\'3 about 155lbs and I carry all my weight in my upper body. When I put it on I felt like it thinned me put and I got so many compliments.',
      star: 4,
      time: 'August 14, 2019')
];
final List<XDeliveryMethod> listDeliveryMethod = [
  XDeliveryMethod(
    id: '1',
    image:
        'https://firebasestorage.googleapis.com/v0/b/e-conmmerce.appspot.com/o/delivery%2Ffedex.png?alt=media&token=9a15de93-a6da-404c-8889-6cda68b3404b',
    shippingFromDate: 2,
    shippingToDate: 3,
    name: 'FedEx',
    price: 15,
  ),
  XDeliveryMethod(
    id: '2',
    image:
        'https://firebasestorage.googleapis.com/v0/b/e-conmmerce.appspot.com/o/delivery%2Fusps.png?alt=media&token=a84c75e9-897e-4be4-9e37-71d244d8d2ec',
    shippingFromDate: 2,
    shippingToDate: 3,
    name: 'USPS',
    price: 20,
  ),
  XDeliveryMethod(
    id: '3',
    image:
        'https://firebasestorage.googleapis.com/v0/b/e-conmmerce.appspot.com/o/delivery%2Fdhl.png?alt=media&token=1e3ef0c1-773c-4a08-8c05-42dfbb817be8',
    shippingFromDate: 2,
    shippingToDate: 4,
    name: 'DHL',
    price: 17,
  ),
];
